/**
 * The committed parity references must match the live TypeScript engine.
 *
 * `analysis/tests/reference/*.output.json` is what the Python suite asserts
 * equality against. Those files are generated by
 * `scripts/dump-analysis-reference.ts` and then committed, so nothing else
 * ties them to `analyseTier0()`: a change to the TypeScript engine would leave
 * `npm run test:analysis` green against stale references while the two live
 * engines disagreed. This test recomputes every case and fails on any drift,
 * which is the signal to re-run the dump script and re-check parity.
 */
import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';
import { analysisRequest, analyseTier0 } from './engine.js';
import { loadEvidenceBundle } from './fixtures.js';
import { REFERENCE_CASES, REFERENCE_DIR } from './analysis-reference-cases.js';

const { plan, evidence } = loadEvidenceBundle();
const cases = REFERENCE_CASES(plan, evidence.tier0);

describe('committed analysis references', () => {
  it.each(cases.map((c) => c.name))('%s output matches the live engine', (name) => {
    const c = cases.find((x) => x.name === name)!;
    const committed = JSON.parse(readFileSync(`${REFERENCE_DIR}/${name}.output.json`, 'utf8'));
    expect(analyseTier0(c.plan, c.tier0)).toEqual(committed);
  });

  it.each(cases.map((c) => c.name))('%s request hashes match the live engine', (name) => {
    const c = cases.find((x) => x.name === name)!;
    const committed = JSON.parse(readFileSync(`${REFERENCE_DIR}/${name}.request.json`, 'utf8'));
    const req = analysisRequest(c.plan, c.tier0);
    expect(req.planHash).toBe(committed.planHash);
    expect(req.snapshotHash).toBe(committed.snapshotHash);
    expect(req.planCanonical).toBe(committed.planCanonical);
    // The snapshot itself is stored once, gzipped, and referenced by hash.
    const stored = gunzipSync(readFileSync(`${REFERENCE_DIR}/${committed.tier0CanonicalFile}`)).toString('utf8');
    expect(stored).toBe(req.tier0Canonical);
  });
});
